name: ci
on: [push, pull_request]
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn test
